### ISSUE TITLE
Feature request - valve details

### ISSUE THREAD

**Issue by marekbrezina** [tomtomfx/wiserSmartForHA#1]
Hello Thomas, many thanks for your great HACS.

I have found it very usefull - instead of rest sensors I can use this incredible integration. 

I have a question and a request to you. I have my heating zones equiped with radiator valves (EH-ZB-VACT) and therefore the get_all_loc_temp returns also data about the valve - valvePosition (0-100%),  callibrationStatus (0 - 1) and internalTemp 
Unfortunately there is no identification of a device (id or whatever) - just list of valves in zone and their status. 

Would you be so glad to enable reading of these attributes as another thermostat entity? 

My programming skills are unfortunatelly not good enough to make it.

See example of response attached
[get_all_loc_temp_response.txt](https://github.com/tomtomfx/wiserSmartForHA/files/5336479/get_all_loc_temp_response.txt)

cheers Marek

**Comment by tomtomfx** [comment]
Hi Marek,

Thanks for the feedback.
I can try to help here. 

I'll update the python library used to connect to the Wiser gateway to retrieve the valve information.
As I do not have these at home, would you be able to test the python library and provide the results?

Then once the python library works I can try and add it to the HACS component.

Just out of curiosity, how the valves are displayed/part of the home assistant? Could you share screenshots of the devices/entities?

Cheers,
Thomas.

**Comment by tomtomfx** [comment]
OK this could be easier than what I thought.
The python library should send the data to home assistant already just need to extract it.

It would be really good if you can send me some screenshots on how your devices are defined in HA so I can try to add what is missing.

Cheers,
Thomas.

**Comment by tomtomfx** [comment]
Could you also send me what "http://{}/rpc/homedevice/device_list" returns?

**Comment by marekbrezina** [comment]
Hello Thomas,
wow, you are very active :) I really appreciate. 
Here is the device list response. 
[device_list_response.txt](https://github.com/tomtomfx/wiserSmartForHA/files/5343630/device_list_response.txt)
I believe I can test the python library before updating the hacs integration. 
cheers Marek

**Comment by marekbrezina** [comment]
Hi again,
this is how the list of entiities with some VACTs look - I believe it uses the icons defined by you for HACT 
![HA_Wiser](https://user-images.githubusercontent.com/43824714/95385056-bdd42380-08ed-11eb-8f80-6689519c7512.JPG)

**Comment by tomtomfx** [comment]
Hi Marek,

So after reviewing the code it should not be that complex to add the information.
However I have one main problem. You have one room where you have three valves and I do not see a way to know which information correspond to which valve.

Could you show me what information you have in this:
![image](https://user-images.githubusercontent.com/582588/95607642-5a1c3880-0a5c-11eb-88b5-9e8da97679d0.png)

Thanks,
Thomas.

**Comment by marekbrezina** [comment]
Hello Thomas,
I am afraid there is no way to anyhow bind the valve in a zone to a VACT device, simply there is ID missing. But I can live with that. I would be happy to see the valves positions as part of a thermostat - just a lis like valve 1 - position 80% - calibration status =1, valve 2 - position 75% etc... t, this would be great. It is not so important to know which valve it is exactly.  

There are no information about the UIO available. The UIO is mains powered. It has one Ouput used to command (ON/OFF) the boiler based on the heat demand generated by thermostats (using the valve position) . It has two inputs configurable as alarms in case of fire  or gas leak (using external sensor switching the input)
I am afraid there is no RPC to read the input or output status as of my knowledge. 

regards Marek
![UIO](https://user-images.githubusercontent.com/43824714/95625230-76c66980-0a78-11eb-9dc0-490faf64d3a7.JPG)

**Comment by tomtomfx** [comment]
Hi Marek,

I've update the code to add some attributes to the climate/thermostat and add the valves status in these climate.
Issue is that I'm not able to test it as I do not have the valves myself.

So I commited the change on the master and try an update on my system to check if there was any regression.
So far so good...

If you could try going on the "master" (not sure which version you are using today) and restart you HA system that would be a good test.

Please send me the logs of HA if any issue.

Regards,
Thomas.

**Comment by marekbrezina** [comment]
Hi Thomas, there seems to be a typo:

> Error while setting up wisersmart platform for climate
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 522, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/config/custom_components/wisersmart/climate.py", line 171, in state_attributes
>     attrs["valvePosition_" + i] = valve.get("valvePosition")
> TypeError: can only concatenate str (not "int") to str
>

**Comment by tomtomfx** [comment]
Hi Marek,

Thanks for testing. Sorry it didn't work but this is the issue of not having these to test locally.

Good news is that I just fixed this issue (hopefully the only one) so you can test again when possible.
The other good news is that if it failed there it means that the data is present and can probably be displayed in HA easily.

Thomas.

**Comment by marekbrezina** [comment]
Hi Thomas, we are movig ahead, thats great. I can see the thermostats again in the entiites. There are some other isssues in the log.

Logger: homeassistant.components.climate
Source: custom_components/wisersmart/climate.py:125
Integration: Klimatizace (documentation, issues)
First occurred: 22:02:49 (2 occurrences)
Last logged: 22:04:21
Error while setting up wisersmart platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 414, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/wisersmart/climate.py", line 125, in icon
    if self.current_temp < self.target_temp:
TypeError: '<' not supported between instances of 'float' and 'NoneType'

And othter 


Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:473
Integration: Spínač (documentation, issues)
First occurred: 22:04:21 (5 occurrences)
Last logged: 22:04:21

    Platform wisersmart does not generate unique IDs. ID WiserSmart - Spd2 Koupelna already exists - ignoring switch.wisersmart_plug_spd2_koupelna
    Platform wisersmart does not generate unique IDs. ID WiserSmart - Lact Bojler already exists - ignoring switch.wisersmart_plug_lact_bojler
    Platform wisersmart does not generate unique IDs. ID WiserSmart - Spd Kotel already exists - ignoring switch.wisersmart_plug_spd_kotel
    Platform wisersmart does not generate unique IDs. ID WiserSmart - Spd Obyvak already exists - ignoring switch.wisersmart_plug_spd_obyvak
    Platform wisersmart does not generate unique IDs. ID WiserSmart - Spd1 Lihen already exists - ignoring switch.wisersmart_plug_spd1_lihen

and other 


Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:473
Integration: Senzor (documentation, issues)
First occurred: 22:04:21 (43 occurrences)
Last logged: 22:04:21

    Platform wisersmart does not generate unique IDs. ID Battery-RTS_Loznice already exists - ignoring sensor.wisersmart_rts_loznice_battery_level
    Platform wisersmart does not generate unique IDs. ID EH-ZB-VACT-VACT_Koupelna already exists - ignoring sensor.wisersmart_vact_koupelna
    Platform wisersmart does not generate unique IDs. ID Battery-VACT_Koupelna already exists - ignoring sensor.wisersmart_vact_koupelna_battery_level
    Platform wisersmart does not generate unique IDs. ID Cloud Sensor-0 already exists - ignoring sensor.wiser_smart_cloud_status
    Platform wisersmart does not generate unique IDs. ID Operation Mode-0 already exists - ignoring sensor.wiser_operation_mode


and last one


Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:473
Integration: Klimatizace (documentation, issues)
First occurred: 22:04:21 (8 occurrences)
Last logged: 22:04:21

    Platform wisersmart does not generate unique IDs. ID WiserSmartRoom - Hala already exists - ignoring climate.wisersmart_thermostat_hala
    Platform wisersmart does not generate unique IDs. ID WiserSmartRoom - Obyvak rodice already exists - ignoring climate.wisersmart_thermostat_obyvak_rodice
    Platform wisersmart does not generate unique IDs. ID WiserSmartRoom - Loznice already exists - ignoring climate.wisersmart_thermostat_loznice
    Platform wisersmart does not generate unique IDs. ID WiserSmartRoom - Loznice rodice already exists - ignoring climate.wisersmart_thermostat_loznice_rodice
    Platform wisersmart does not generate unique IDs. ID WiserSmartRoom - Schodiste already exists - ignoring climate.wisersmart_thermostat_schodiste

**Comment by tomtomfx** [comment]
I'm not sure what the issue is. 
As the latest upgrade went wrong could you try removing the integration, then restart HA then re-installing it?
It is a bit cumbersome but I think this will give better logs compare to these.

I forgot but you also need to remove orphan entities after restart if any.

**Comment by marekbrezina** [comment]
Hello Thomas, 
I have uninstalled the integration, restarted the controller and checked the orphans (none found)
Then I installed the integration, setup the connection to the controller.
However there is an error logged again. 
Could it be related to any timeout issue? I have many devices so it takes some time to get the response. Maybe there is no instance of the object yet (but I do not know python well so I might be completely wrong...)

Thanks Marek

```
Logger: homeassistant.components.climate
Source: custom_components/wisersmart/climate.py:125
Integration: Klimatizace (documentation, issues)
First occurred: 12:20:50 (1 occurrences)
Last logged: 12:20:50
Error while setting up wisersmart platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 414, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/wisersmart/climate.py", line 125, in icon
    if self.current_temp < self.target_temp:
TypeError: '<' not supported between instances of 'float' and 'NoneType'


```

**Comment by tomtomfx** [comment]
Hi Marek,

Sorry for the delay I was on another (work related) project.

This indeed looks like an uninitialized value, I'm going to look into this.

Are the climate (thermostat) devices created and working?
If they are created could you send me a screenshot of the entity details?
If you go to the developer tools and look for the state of this entity what is raised?

Thanks,
Thomas.

**Comment by tomtomfx** [comment]
Hi Marek,

I've looked at the code and the initial response from get_all_loc. 
You have some rooms with no target value set. The error you see there is probably linked and was probably present before.
I've updated the code to initialize the value to -1 if undefined so that should avoid this error in the logs.

Happy if you can test it.

Regards,
Thomas.

**Comment by marekbrezina** [comment]
Hi Thomas,
you are definitely right. I have checked the thermostat attributes and there are valve positions etc. already available. 
Great. Many thanks. Now I need to learn how to use these values. 
cheers
Marek

![thermostat_attributes](https://user-images.githubusercontent.com/43824714/96548121-972ec900-12ad-11eb-889e-1cda54f8fbb5.JPG)

**Comment by tomtomfx** [comment]
OK perfect. 
I'll do an official release then 0.9.4.
T.

**Comment by tomtomfx** [comment]
Delivered in v0.9.4.
